stages:
  - release

release:
  before_script:
    - yarn install --frozen-lockfile
    - apk add --no-cache git
    - git config --global user.email "yevhenlisovenko@gmail.com"
    - git config --global user.name "Yevhen L."
    - git fetch origin +refs/heads/master:refs/remotes/origin/master;
    - git checkout master;
    - git reset --hard "$CI_COMMIT_SHA";
  image: node:12-alpine
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules
  only:
    - master
  script:
    - yarn pkg
  stage: release
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skiprelease\]/i
  when: on_success

  