stages:
  - release

release:
  before_script:
    - yarn install --frozen-lockfile
    - apk add --no-cache git
  image: node:12-alpine
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules
  only:
    - master
  script:
    - git fetch origin +refs/heads/master:refs/remotes/origin/master
    - git checkout master
    - yarn lerna version --conventional-commits --no-git-tag-version --no-push --tag-version-prefix='' --yes
    - yarn build:ui
    - yarn build:ui:docs
    - GITLAB_TOKEN=${GITLAB_TOKEN} npx semantic-release --branch master
    - yarn lerna publish from-git --no-changelog --tag-version-prefix='' --yes
  stage: release
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skiprelease\]/i
  when: on_success