stages:
  - release

release:
  before_script:
    - yarn install --frozen-lockfile
    - apk add --no-cache git
    - git config --global user.email "yevhenlisovenko@gmail.com"
    - git config --global user.name "Yevhen L."
  image: node:12-alpine
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules
  only:
    - master
  script:
    - yarn build:ui
    - yarn build:ui:docs
    - GL_TOKEN=${GITLAB_TOKEN} GL_API_URL=https://git.awescode.com/api/v4 yarn lerna version --amend --conventional-commits --create-release gitlab --yes
  stage: release
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skiprelease\]/i
  when: on_success

  