stages:
  - release

release:
  before_script:
    - yarn install --frozen-lockfile
    - apk add --no-cache git
    - git config --global user.email "yevhenlisovenko@gmail.com"
    - git config --global user.name "Yevhen L."
    - git status
    - git remote set-url origin https://gitlab-ci-token:${GITLAB_TOKEN}@git.awescode.com/awes-io/client.git
    - git checkout master
    - git status
  image: node:12-alpine
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules
  only:
    - master
  script:
    - yarn lerna version --conventional-commits --no-git-tag-version --no-push --tag-version-prefix='' --yes
    - yarn build:ui
    - yarn build:ui:docs
    - git add .
    - git commit -m "chore:\ released a new version [skiprelease]"
    - git push origin master
    - yarn lerna publish from-git --no-changelog --tag-version-prefix='' --yes
  stage: release
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skiprelease\]/i
  when: on_success